export const DUAS = [
  { id:1, title:"Dua beim Aufwachen", category:"Morgen", emoji:"🌅", arabic:"الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", transliteration:"Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur", translation:"Alles Lob gebührt Allah, Der uns lebendig gemacht hat, nachdem Er uns hat sterben lassen, und zu Ihm ist die Auferstehung." },
  { id:2, title:"Dua vor dem Essen", category:"Essen", emoji:"🍽", arabic:"بِسْمِ اللَّهِ وَبَرَكَةِ اللَّهِ", transliteration:"Bismillahi wa barakatillah", translation:"Im Namen Allahs und mit dem Segen Allahs." },
  { id:3, title:"Dua nach dem Essen", category:"Essen", emoji:"🍽", arabic:"الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", transliteration:"Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimin", translation:"Alles Lob gebührt Allah, Der uns gespeist und getränkt und uns zu Muslimen gemacht hat." },
  { id:4, title:"Dua beim Verlassen des Hauses", category:"Alltag", emoji:"🚪", arabic:"بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration:"Bismillahi tawakkaltu alallahi wa la hawla wa la quwwata illa billah", translation:"Im Namen Allahs, ich vertraue auf Allah, und es gibt keine Macht und keine Kraft außer bei Allah." },
  { id:5, title:"Dua beim Betreten der Moschee", category:"Moschee", emoji:"🕌", arabic:"اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", transliteration:"Allahumma iftah li abwaba rahmatik", translation:"O Allah, öffne mir die Tore Deiner Barmherzigkeit." },
  { id:6, title:"Istighfar (Vergebung)", category:"Dhikr", emoji:"💎", arabic:"أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ", transliteration:"Astaghfirullaha al-Adheemal-ladhi la ilaha illa Huwal-Hayyul-Qayyumu wa atubu ilayh", translation:"Ich bitte Allah, den Gewaltigen, um Vergebung, den Lebendigen, den Beständigen, und ich wende mich Ihm reuig zu." },
  { id:7, title:"Dua vor dem Schlafen", category:"Abend", emoji:"🌙", arabic:"بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration:"Bismika Allahumma amutu wa ahya", translation:"In Deinem Namen, o Allah, sterbe ich und lebe ich." },
  { id:8, title:"Ayatul Kursi", category:"Schutz", emoji:"🛡", arabic:"اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ", transliteration:"Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bi-shay'in min 'ilmihi illa bima sha'. Wasi'a kursiyyuhus-samawati wal-ard. Wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.", translation:"Allah - es gibt keinen Gott außer Ihm, dem Lebendigen, dem Beständigen. Ihn überkommt weder Schlummer noch Schlaf. Ihm gehört, was in den Himmeln und was auf der Erde ist. Wer ist es, der bei Ihm Fürsprache einlegen könnte außer mit Seiner Erlaubnis? Er weiß, was vor ihnen und was hinter ihnen liegt. Und sie umfassen nichts von Seinem Wissen, außer was Er will. Sein Thron umfasst die Himmel und die Erde. Und ihre Bewahrung fällt Ihm nicht schwer. Und Er ist der Erhabene, der Gewaltige." },
  { id:9, title:"Dua für die Eltern", category:"Familie", emoji:"❤️", arabic:"رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", transliteration:"Rabbir-hamhuma kama rabbayanee sagheera", translation:"Mein Herr, erbarme Dich ihrer, so wie sie mich aufgezogen haben, als ich klein war." },
  { id:10, title:"Dua in schwierigen Zeiten", category:"Trost", emoji:"🤍", arabic:"حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", transliteration:"Hasbunallahu wa ni'mal-wakeel", translation:"Allah genügt uns, und Er ist der beste Sachwalter." },
  { id:11, title:"Dua beim Reisen", category:"Reise", emoji:"✈️", arabic:"سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ", transliteration:"Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin", translation:"Preis sei Dem, Der uns dies dienstbar gemacht hat, denn wir hätten es nicht vermocht." },
];
