// Letzte Verifizierung: 2026-03-27
// Duas: geprüft gegen Hisn al-Muslim / Sahih Hadith-Quellen
// Quran-Verse in Duas: geprüft gegen Uthmani-Mushaf
export const DUAS = [
  // ═══════════════════════════════════════
  // Kategorie 1: Morgen 🌅
  // ═══════════════════════════════════════
  {
    id: 1,
    title: "Dua beim Aufwachen",
    category: "Morgen",
    emoji: "🌅",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation: "Alles Lob gebührt Allah, Der uns lebendig gemacht hat, nachdem Er uns hat sterben lassen, und zu Ihm ist die Auferstehung.",
    source: "Sahih al-Bukhari 6312",
  },
  {
    id: 2,
    title: "Morgen-Dhikr",
    category: "Morgen",
    emoji: "🌅",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation: "Wir sind in den Morgen eingetreten und die Herrschaft gehört Allah. Alles Lob gebührt Allah. Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und Ihm gebührt das Lob, und Er hat Macht über alle Dinge.",
    source: "Sahih Muslim 2723",
  },
  {
    id: 3,
    title: "Sayyid al-Istighfar (Morgens)",
    category: "Morgen",
    emoji: "🌅",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliteration: "Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bi-ni'matika 'alayya wa abu'u bi-dhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa anta",
    translation: "O Allah, Du bist mein Herr. Es gibt keinen Gott außer Dir. Du hast mich erschaffen und ich bin Dein Diener. Ich halte an Deinem Bund und Deinem Versprechen fest, so gut ich kann. Ich suche Zuflucht bei Dir vor dem Übel meiner Taten. Ich bekenne Deine Gunst mir gegenüber und bekenne meine Sünde. So vergib mir, denn niemand vergibt die Sünden außer Dir.",
    source: "Sahih al-Bukhari 6306",
  },
  {
    id: 4,
    title: "Morgen-Bittgebet",
    category: "Morgen",
    emoji: "🌅",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna wa bika amsayna, wa bika nahya wa bika namutu wa ilaykan-nushur",
    translation: "O Allah, durch Dich treten wir in den Morgen ein und durch Dich treten wir in den Abend ein. Durch Dich leben wir und durch Dich sterben wir, und zu Dir ist die Auferstehung.",
    source: "Sunan at-Tirmidhi 3391",
  },

  // ═══════════════════════════════════════
  // Kategorie 2: Abend 🌙
  // ═══════════════════════════════════════
  {
    id: 5,
    title: "Dua vor dem Schlafen",
    category: "Abend",
    emoji: "🌙",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Deinem Namen, o Allah, sterbe ich und lebe ich.",
    source: "Sahih al-Bukhari 6314",
  },
  {
    id: 6,
    title: "Abend-Dhikr",
    category: "Abend",
    emoji: "🌙",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation: "Wir sind in den Abend eingetreten und die Herrschaft gehört Allah. Alles Lob gebührt Allah. Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und Ihm gebührt das Lob, und Er hat Macht über alle Dinge.",
    source: "Sahih Muslim 2723",
  },
  {
    id: 7,
    title: "Dua gegen Sorgen und Traurigkeit",
    category: "Abend",
    emoji: "🌙",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wa a'udhu bika minal-'ajzi wal-kasal, wa a'udhu bika minal-jubni wal-bukhl, wa a'udhu bika min ghalabatid-dayni wa qahrir-rijal",
    translation: "O Allah, ich suche Zuflucht bei Dir vor Sorge und Traurigkeit, vor Unfähigkeit und Faulheit, vor Feigheit und Geiz, und vor der Überwältigung durch Schulden und der Unterdrückung durch Menschen.",
    source: "Sahih al-Bukhari 6369",
  },
  {
    id: 8,
    title: "Abend-Bittgebet",
    category: "Abend",
    emoji: "🌙",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transliteration: "Allahumma bika amsayna wa bika asbahna, wa bika nahya wa bika namutu wa ilaykal-masir",
    translation: "O Allah, durch Dich treten wir in den Abend ein und durch Dich treten wir in den Morgen ein. Durch Dich leben wir und durch Dich sterben wir, und zu Dir ist die Rückkehr.",
    source: "Sunan at-Tirmidhi 3391",
  },

  // ═══════════════════════════════════════
  // Kategorie 3: Gebet 🕌
  // ═══════════════════════════════════════
  {
    id: 9,
    title: "Dua beim Betreten der Moschee",
    category: "Gebet",
    emoji: "🕌",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahumma iftah li abwaba rahmatik",
    translation: "O Allah, öffne mir die Tore Deiner Barmherzigkeit.",
    source: "Sahih Muslim 713",
  },
  {
    id: 10,
    title: "Dua beim Verlassen der Moschee",
    category: "Gebet",
    emoji: "🕌",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "Allahumma inni as'aluka min fadlik",
    translation: "O Allah, ich bitte Dich um Deine Gunst.",
    source: "Sahih Muslim 713",
  },
  {
    id: 11,
    title: "Dua zwischen Adhan und Iqama",
    category: "Gebet",
    emoji: "🕌",
    arabic: "اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    transliteration: "Allahumma Rabba hadhihid-da'watit-tammah, was-salatil-qa'imah, ati Muhammadanil-wasilata wal-fadilah, wab'athhu maqamam-mahmudan alladhi wa'adtah",
    translation: "O Allah, Herr dieses vollkommenen Rufes und des bevorstehenden Gebets, gewähre Muhammad die Fürsprache und die Vorzüglichkeit, und erwecke ihn zu dem lobenswerten Rang, den Du ihm versprochen hast.",
    source: "Sahih al-Bukhari 614",
  },
  {
    id: 12,
    title: "Dua im Sujud (Niederwerfung)",
    category: "Gebet",
    emoji: "🕌",
    arabic: "سُبْحَانَ رَبِّيَ الْأَعْلَىٰ",
    transliteration: "Subhana Rabbiyal-A'la",
    translation: "Preis sei meinem Herrn, dem Allerhöchsten.",
    source: "Sahih Muslim 772",
  },
  {
    id: 13,
    title: "Dua nach dem Tashahhud",
    category: "Gebet",
    emoji: "🕌",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ جَهَنَّمَ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ",
    transliteration: "Allahumma inni a'udhu bika min 'adhabil-qabri, wa min 'adhabi jahannam, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-masihid-dajjal",
    translation: "O Allah, ich suche Zuflucht bei Dir vor der Strafe des Grabes, vor der Strafe der Hölle, vor der Versuchung des Lebens und des Todes und vor dem Übel der Versuchung des Dajjal.",
    source: "Sahih Muslim 588",
  },

  // ═══════════════════════════════════════
  // Kategorie 4: Essen 🍽
  // ═══════════════════════════════════════
  {
    id: 14,
    title: "Dua vor dem Essen",
    category: "Essen",
    emoji: "🍽",
    arabic: "بِسْمِ اللَّهِ",
    transliteration: "Bismillah",
    translation: "Im Namen Allahs. (Wenn vergessen: بِسْمِ اللَّهِ فِي أَوَّلِهِ وَآخِرِهِ — Im Namen Allahs, am Anfang und am Ende.)",
    source: "Sunan Abu Dawud 3767, Sunan at-Tirmidhi 1858",
  },
  {
    id: 15,
    title: "Dua nach dem Essen",
    category: "Essen",
    emoji: "🍽",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "Alles Lob gebührt Allah, Der mir dies zu essen gab und mich damit versorgte, ohne Macht und Kraft von mir.",
    source: "Sunan Abu Dawud 4023, Sunan at-Tirmidhi 3458",
  },
  {
    id: 16,
    title: "Dua beim Fastenbrechen (Iftar)",
    category: "Essen",
    emoji: "🍽",
    arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
    transliteration: "Dhahabadh-dhama'u wabtallatil-'uruqu wa thabatal-ajru in sha'Allah",
    translation: "Der Durst ist vergangen, die Adern sind befeuchtet und die Belohnung ist sicher, so Allah will.",
    source: "Sunan Abu Dawud 2357",
  },
  {
    id: 17,
    title: "Dua wenn bei jemandem eingeladen",
    category: "Essen",
    emoji: "🍽",
    arabic: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي",
    transliteration: "Allahumma at'im man at'amani wasqi man saqani",
    translation: "O Allah, speise den, der mich gespeist hat, und gib dem zu trinken, der mir zu trinken gab.",
    source: "Sahih Muslim 2055",
  },

  // ═══════════════════════════════════════
  // Kategorie 5: Reise ✈️
  // ═══════════════════════════════════════
  {
    id: 18,
    title: "Dua beim Reisen",
    category: "Reise",
    emoji: "✈️",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ",
    transliteration: "Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun",
    translation: "Preis sei Dem, Der uns dies dienstbar gemacht hat, denn wir hätten es nicht vermocht. Und zu unserem Herrn werden wir gewiss zurückkehren.",
    source: "Quran 43:13-14",
  },
  {
    id: 19,
    title: "Dua beim Einsteigen in ein Fahrzeug",
    category: "Reise",
    emoji: "✈️",
    arabic: "بِسْمِ اللَّهِ وَالْحَمْدُ لِلَّهِ سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ",
    transliteration: "Bismillah, walhamdu lillah. Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun",
    translation: "Im Namen Allahs, und alles Lob gebührt Allah. Preis sei Dem, Der uns dies dienstbar gemacht hat, denn wir hätten es nicht vermocht. Und zu unserem Herrn werden wir gewiss zurückkehren.",
    source: "Sunan at-Tirmidhi 3446",
  },
  {
    id: 20,
    title: "Dua bei Ankunft an einem neuen Ort",
    category: "Reise",
    emoji: "✈️",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bi kalimatillahit-tammati min sharri ma khalaq",
    translation: "Ich suche Zuflucht bei den vollkommenen Worten Allahs vor dem Übel dessen, was Er erschaffen hat.",
    source: "Sahih Muslim 2708",
  },
  {
    id: 21,
    title: "Dua für den Reisenden",
    category: "Reise",
    emoji: "✈️",
    arabic: "أَسْتَوْدِعُكَ اللَّهَ الَّذِي لَا تَضِيعُ وَدَائِعُهُ",
    transliteration: "Astawdi'ukallaha alladhi la tadi'u wada'i'uh",
    translation: "Ich vertraue dich Allah an, bei Dem nichts verloren geht, was Ihm anvertraut wurde.",
    source: "Sunan Ibn Majah 2825",
  },

  // ═══════════════════════════════════════
  // Kategorie 6: Schutz 🛡
  // ═══════════════════════════════════════
  {
    id: 22,
    title: "Ayatul Kursi",
    category: "Schutz",
    emoji: "🛡",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bi-shay'in min 'ilmihi illa bima sha'. Wasi'a kursiyyuhus-samawati wal-ard. Wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.",
    translation: "Allah - es gibt keinen Gott außer Ihm, dem Lebendigen, dem Beständigen. Ihn überkommt weder Schlummer noch Schlaf. Ihm gehört, was in den Himmeln und was auf der Erde ist. Wer ist es, der bei Ihm Fürsprache einlegen könnte außer mit Seiner Erlaubnis? Er weiß, was vor ihnen und was hinter ihnen liegt. Und sie umfassen nichts von Seinem Wissen, außer was Er will. Sein Thron umfasst die Himmel und die Erde. Und ihre Bewahrung fällt Ihm nicht schwer. Und Er ist der Erhabene, der Gewaltige.",
    source: "Quran 2:255",
  },
  {
    id: 23,
    title: "Die drei Qul-Suren (Schutz)",
    category: "Schutz",
    emoji: "🛡",
    arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    transliteration: "Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.",
    translation: "Sprich: Er ist Allah, der Eine. Allah, der Absolute. Er zeugt nicht und ist nicht gezeugt worden. Und Ihm ebenbürtig ist keiner. (Al-Ikhlas — zusammen mit Al-Falaq und An-Nas dreimal morgens und abends als Schutz rezitieren)",
    source: "Quran 112:1-4, Sunan Abu Dawud 5082",
  },
  {
    id: 24,
    title: "Dua gegen den bösen Blick",
    category: "Schutz",
    emoji: "🛡",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    transliteration: "A'udhu bi kalimatillahit-tammah min kulli shaytanin wa hammah wa min kulli 'aynin lammah",
    translation: "Ich suche Zuflucht bei den vollkommenen Worten Allahs vor jedem Teufel und giftigen Wesen und vor jedem neidischen bösen Blick.",
    source: "Sahih al-Bukhari 3371",
  },
  {
    id: 25,
    title: "Schutz-Dua am Abend",
    category: "Schutz",
    emoji: "🛡",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bi kalimatillahit-tammati min sharri ma khalaq",
    translation: "Ich suche Zuflucht bei den vollkommenen Worten Allahs vor dem Übel dessen, was Er erschaffen hat.",
    source: "Sahih Muslim 2708",
  },
  {
    id: 26,
    title: "Dua bei Angst",
    category: "Schutz",
    emoji: "🛡",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
    transliteration: "La ilaha illallahul-'Adhimul-Halim. La ilaha illallahu Rabbul-'Arshil-'Adhim. La ilaha illallahu Rabbus-samawati wa Rabbul-ardi wa Rabbul-'Arshil-Karim",
    translation: "Es gibt keinen Gott außer Allah, dem Gewaltigen, dem Nachsichtigen. Es gibt keinen Gott außer Allah, dem Herrn des gewaltigen Throns. Es gibt keinen Gott außer Allah, dem Herrn der Himmel und dem Herrn der Erde und dem Herrn des edlen Throns.",
    source: "Sahih al-Bukhari 6346",
  },

  // ═══════════════════════════════════════
  // Kategorie 7: Familie ❤️
  // ═══════════════════════════════════════
  {
    id: 27,
    title: "Dua für die Eltern",
    category: "Familie",
    emoji: "❤️",
    arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbir-hamhuma kama rabbayanee sagheera",
    translation: "Mein Herr, erbarme Dich ihrer, so wie sie mich aufgezogen haben, als ich klein war.",
    source: "Quran 17:24",
  },
  {
    id: 28,
    title: "Dua für die Kinder",
    category: "Familie",
    emoji: "❤️",
    arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
    transliteration: "Rabbi hab li minas-salihin",
    translation: "Mein Herr, schenke mir (Nachkommen) von den Rechtschaffenen.",
    source: "Quran 37:100",
  },
  {
    id: 29,
    title: "Dua für den Ehepartner",
    category: "Familie",
    emoji: "❤️",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    translation: "Unser Herr, schenke uns in unseren Gattinnen und unseren Nachkommen Augenfreude und mache uns zu einem Vorbild für die Gottesfürchtigen.",
    source: "Quran 25:74",
  },
  {
    id: 30,
    title: "Dua für einen Verstorbenen",
    category: "Familie",
    emoji: "❤️",
    arabic: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مُدْخَلَهُ",
    transliteration: "Allahummaghfir lahu warhamhu wa 'afihi wa'fu 'anhu wa akrim nuzulahu wa wassi' mudkhalahu",
    translation: "O Allah, vergib ihm und erbarme Dich seiner, gewähre ihm Sicherheit und vergib ihm, ehre seinen Empfang und erweitere seinen Eingang.",
    source: "Sahih Muslim 963",
  },

  // ═══════════════════════════════════════
  // Kategorie 8: Alltag 🏠
  // ═══════════════════════════════════════
  {
    id: 31,
    title: "Dua beim Betreten des Hauses",
    category: "Alltag",
    emoji: "🏠",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'alallahi Rabbina tawakkalna",
    translation: "Im Namen Allahs treten wir ein, im Namen Allahs gehen wir hinaus, und auf Allah, unseren Herrn, vertrauen wir.",
    source: "Sunan Abu Dawud 5096",
  },
  {
    id: 32,
    title: "Dua beim Verlassen des Hauses",
    category: "Alltag",
    emoji: "🏠",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Bismillahi tawakkaltu 'alallahi la hawla wa la quwwata illa billah",
    translation: "Im Namen Allahs, ich vertraue auf Allah, es gibt keine Macht und keine Kraft außer bei Allah.",
    source: "Sunan Abu Dawud 5095, Sunan at-Tirmidhi 3426",
  },
  {
    id: 33,
    title: "Dua beim Anziehen neuer Kleidung",
    category: "Alltag",
    emoji: "🏠",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdu lillahil-ladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "Alles Lob gebührt Allah, Der mich damit bekleidet und mich damit versorgt hat, ohne Macht und Kraft von mir.",
    source: "Sunan Abu Dawud 4023",
  },
  {
    id: 34,
    title: "Dua beim Blick in den Spiegel",
    category: "Alltag",
    emoji: "🏠",
    arabic: "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
    transliteration: "Allahumma anta hassanta khalqi fa-hassin khuluqi",
    translation: "O Allah, so wie Du meine äußere Gestalt schön gemacht hast, so verschönere auch meinen Charakter.",
    source: "Musnad Ahmad 3823",
  },
  {
    id: 35,
    title: "Dua bei Regen",
    category: "Alltag",
    emoji: "🏠",
    arabic: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    transliteration: "Allahumma sayyiban nafi'a",
    translation: "O Allah, (mache es zu) einem nützlichen Regen.",
    source: "Sahih al-Bukhari 1032",
  },

  // ═══════════════════════════════════════
  // Kategorie 9: Wissen 📚
  // ═══════════════════════════════════════
  {
    id: 36,
    title: "Bitte um mehr Wissen",
    category: "Wissen",
    emoji: "📚",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transliteration: "Rabbi zidni 'ilma",
    translation: "Mein Herr, vermehre mein Wissen.",
    source: "Quran 20:114",
  },
  {
    id: 37,
    title: "Dua vor dem Lernen",
    category: "Wissen",
    emoji: "📚",
    arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا",
    transliteration: "Allahumma infa'ni bima 'allamtani wa 'allimni ma yanfa'uni wa zidni 'ilma",
    translation: "O Allah, lass mich Nutzen ziehen aus dem, was Du mich gelehrt hast, lehre mich, was mir nützt, und vermehre mein Wissen.",
    source: "Sunan at-Tirmidhi 3599",
  },
  {
    id: 38,
    title: "Dua nach dem Lernen",
    category: "Wissen",
    emoji: "📚",
    arabic: "اللَّهُمَّ إِنِّي أَسْتَوْدِعُكَ مَا عَلَّمْتَنِي فَارْدُدْهُ إِلَيَّ عِنْدَ حَاجَتِي وَلَا تَنْسَنِيهِ",
    transliteration: "Allahumma inni astawdi'uka ma 'allamtani fardud-hu ilayya 'inda hajati wa la tansanihi",
    translation: "O Allah, ich vertraue Dir an, was Du mich gelehrt hast. So gib es mir zurück, wenn ich es brauche, und lass mich es nicht vergessen.",
    source: "Hisn al-Muslim",
  },
  {
    id: 39,
    title: "Dua für nützliches Wissen",
    category: "Wissen",
    emoji: "📚",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
    transliteration: "Allahumma inni as'aluka 'ilman nafi'a wa rizqan tayyiba wa 'amalan mutaqabbala",
    translation: "O Allah, ich bitte Dich um nützliches Wissen, gute Versorgung und angenommene Taten.",
    source: "Sunan Ibn Majah 925",
  },

  // ═══════════════════════════════════════
  // Kategorie 10: Trost 🤍
  // ═══════════════════════════════════════
  {
    id: 40,
    title: "HasbunAllah",
    category: "Trost",
    emoji: "🤍",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    transliteration: "Hasbunallahu wa ni'mal-wakil",
    translation: "Allah genügt uns, und Er ist der beste Sachwalter.",
    source: "Quran 3:173",
  },
  {
    id: 41,
    title: "Inna lillahi wa inna ilayhi raji'un",
    category: "Trost",
    emoji: "🤍",
    arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
    transliteration: "Inna lillahi wa inna ilayhi raji'un",
    translation: "Wahrlich, wir gehören Allah und zu Ihm kehren wir zurück.",
    source: "Quran 2:156",
  },
  {
    id: 42,
    title: "Dua bei Schwierigkeiten",
    category: "Trost",
    emoji: "🤍",
    arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
    transliteration: "Allahumma la sahla illa ma ja'altahu sahla, wa anta taj'alul-hazna idha shi'ta sahla",
    translation: "O Allah, nichts ist leicht außer dem, was Du leicht gemacht hast. Und Du machst die Trauer leicht, wenn Du willst.",
    source: "Sahih Ibn Hibban 974",
  },
  {
    id: 43,
    title: "Dua bei Trauer und Kummer",
    category: "Trost",
    emoji: "🤍",
    arabic: "لَا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    transliteration: "La ilaha illa anta subhanaka inni kuntu minadh-dhalimin",
    translation: "Es gibt keinen Gott außer Dir. Preis sei Dir! Ich bin wahrlich einer der Ungerechten gewesen.",
    source: "Quran 21:87",
  },
  {
    id: 44,
    title: "La hawla wa la quwwata illa billah",
    category: "Trost",
    emoji: "🤍",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "La hawla wa la quwwata illa billah",
    translation: "Es gibt keine Macht und keine Kraft außer bei Allah.",
    source: "Sahih al-Bukhari 4205",
  },
];
