export const ACHIEVEMENTS = [
  {
    id: 'first_steps',
    icon: 'sparkles',
    name: 'Erste Schritte',
    description: 'App zum ersten Mal geöffnet',
    check: () => true, // always unlocked
  },
  {
    id: 'first_prayer',
    icon: 'business-outline',
    name: 'Erstes Gebet',
    description: 'Erstes Gebet im Tracker markiert',
    check: (s) => s.totalPrayers >= 1,
  },
  {
    id: 'quran_reader',
    icon: 'book-outline',
    name: 'Quran-Leser',
    description: 'Erste Sure gelesen',
    check: (s) => (s.surahsRead || []).length >= 1,
  },
  {
    id: 'dhikr_starter',
    icon: 'radio-button-on-outline',
    name: 'Dhikr-Starter',
    description: '100 Dhikr insgesamt',
    check: (s) => s.totalDhikr >= 100,
  },
  {
    id: 'week_warrior',
    icon: 'flame-outline',
    name: 'Wochenkrieger',
    description: '7 Tage Streak',
    check: (s) => s.longestStreak >= 7,
  },
  {
    id: 'month_master',
    icon: 'star-outline',
    name: 'Monatsmeister',
    description: '30 Tage Streak',
    check: (s) => s.longestStreak >= 30,
  },
  {
    id: 'quran_explorer',
    icon: 'compass-outline',
    name: 'Quran-Entdecker',
    description: '10 verschiedene Suren gelesen',
    check: (s) => (s.surahsRead || []).length >= 10,
  },
  {
    id: 'dhikr_master',
    icon: 'diamond-outline',
    name: 'Dhikr-Meister',
    description: '10.000 Dhikr insgesamt',
    check: (s) => s.totalDhikr >= 10000,
  },
  {
    id: 'fajr_hero',
    icon: 'sunny-outline',
    name: 'Fajr-Held',
    description: '30 Tage Fajr nicht verpasst',
    check: (s) => s.fajrStreak >= 30,
  },
  {
    id: 'khatma',
    icon: 'trophy-outline',
    name: 'Khatma',
    description: 'Alle 114 Suren gelesen',
    check: (s) => (s.surahsRead || []).length >= 114,
  },
  {
    id: 'hafiz_starter',
    icon: 'bulb-outline',
    name: 'Hafiz-Starter',
    description: '10 Verse auswendig gelernt',
    check: (s) => (s.memorizedVerses || []).length >= 10,
  },
  {
    id: 'memory_master',
    icon: 'ribbon-outline',
    name: 'Gedächtnis-Meister',
    description: '30 Verse auswendig gelernt',
    check: (s) => (s.memorizedVerses || []).length >= 30,
  },
];
