// Arabische Texte verifiziert: 2026-03-27
export const MORNING_ADHKAR = [
  {
    id: 1,
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta\'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa\'u \'indahu illa bi-idhnih. Ya\'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bi-shay\'in min \'ilmihi illa bima sha\'. Wasi\'a kursiyyuhus-samawati wal-ard. Wa la ya\'uduhu hifdhuhuma. Wa Huwal-\'Aliyyul-\'Adhim.',
    translation: 'Allah - es gibt keinen Gott außer Ihm, dem Lebendigen, dem Beständigen. Ihn überkommt weder Schlummer noch Schlaf. Ihm gehört alles in den Himmeln und auf der Erde. Sein Thron umfasst die Himmel und die Erde, und ihre Bewahrung fällt Ihm nicht schwer. Er ist der Erhabene, der Gewaltige.',
    repetitions: 1,
    source: 'Quran 2:255',
  },
  {
    id: 2,
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: 'Sprich: Er ist Allah, der Eine. Allah, der Absolute. Er zeugt nicht und ist nicht gezeugt worden. Und Ihm ebenbürtig ist keiner.',
    repetitions: 3,
    source: 'Quran 112:1-4',
  },
  {
    id: 3,
    arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: 'Qul a\'udhu bi-Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-\'uqad. Wa min sharri hasidin idha hasad.',
    translation: 'Sprich: Ich suche Zuflucht beim Herrn des Tagesanbruchs. Vor dem Übel dessen, was Er erschaffen hat. Vor dem Übel der Dunkelheit, wenn sie hereinbricht. Vor dem Übel der Knotenanbläserinnen. Vor dem Übel des Neiders, wenn er neidet.',
    repetitions: 3,
    source: 'Quran 113:1-5',
  },
  {
    id: 4,
    arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ',
    transliteration: 'Qul a\'udhu bi-Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.',
    translation: 'Sprich: Ich suche Zuflucht beim Herrn der Menschen. Dem König der Menschen. Dem Gott der Menschen. Vor dem Übel des sich zurückziehenden Einflüsterers. Der in die Herzen der Menschen einflüstert. Von den Dschinn und den Menschen.',
    repetitions: 3,
    source: 'Quran 114:1-6',
  },
  {
    id: 5,
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Wir sind in den Morgen eingetreten und die Herrschaft gehört Allah. Alles Lob gebührt Allah. Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 1,
    source: 'Sahih Muslim 2723',
  },
  {
    id: 6,
    arabic: 'اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَٰهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ',
    transliteration: 'Allahumma inni asbahtu ush-hiduka wa ush-hidu hamalata \'arshika wa mala\'ikataka wa jami\'a khalqika annaka antallahu la ilaha illa anta wahdaka la sharika laka wa anna Muhammadan \'abduka wa rasuluk.',
    translation: 'O Allah, ich bin in den Morgen eingetreten und rufe Dich zum Zeugen an, und die Träger Deines Throns, Deine Engel und all Deine Schöpfung, dass Du Allah bist, es keinen Gott gibt außer Dir, allein ohne Partner, und dass Muhammad Dein Diener und Gesandter ist.',
    repetitions: 1,
    source: 'Sunan Abu Dawud 5069',
  },
  {
    id: 7,
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana \'abduka, wa ana \'ala \'ahdika wa wa\'dika mastata\'tu, a\'udhu bika min sharri ma sana\'tu, abu\'u laka bi-ni\'matika \'alayya wa abu\'u bi-dhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa anta.',
    translation: 'O Allah, Du bist mein Herr. Es gibt keinen Gott außer Dir. Du hast mich erschaffen und ich bin Dein Diener. Ich halte an Deinem Bund und Deinem Versprechen fest, so gut ich kann. Ich suche Zuflucht bei Dir vor dem Übel meiner Taten. Ich bekenne Deine Gunst mir gegenüber und bekenne meine Sünde. So vergib mir, denn niemand vergibt die Sünden außer Dir.',
    repetitions: 1,
    source: 'Sahih al-Bukhari 6306',
  },
  {
    id: 8,
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'SubhanAllahi wa bihamdihi',
    translation: 'Preis sei Allah und Ihm gebührt das Lob.',
    repetitions: 100,
    source: 'Sahih Muslim 2692',
  },
  {
    id: 9,
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 10,
    source: 'Sahih Muslim 2693',
  },
  {
    id: 10,
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translation: 'Preis sei Allah.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 11,
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: 'Alles Lob gebührt Allah.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 12,
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: 'Allah ist größer.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 13,
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 1,
    source: 'Sahih Muslim 595',
  },
];

export const EVENING_ADHKAR = [
  {
    id: 1,
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta\'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa\'u \'indahu illa bi-idhnih. Ya\'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bi-shay\'in min \'ilmihi illa bima sha\'. Wasi\'a kursiyyuhus-samawati wal-ard. Wa la ya\'uduhu hifdhuhuma. Wa Huwal-\'Aliyyul-\'Adhim.',
    translation: 'Allah - es gibt keinen Gott außer Ihm, dem Lebendigen, dem Beständigen. Ihn überkommt weder Schlummer noch Schlaf. Ihm gehört alles in den Himmeln und auf der Erde. Sein Thron umfasst die Himmel und die Erde, und ihre Bewahrung fällt Ihm nicht schwer. Er ist der Erhabene, der Gewaltige.',
    repetitions: 1,
    source: 'Quran 2:255',
  },
  {
    id: 2,
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul Huwallahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: 'Sprich: Er ist Allah, der Eine. Allah, der Absolute. Er zeugt nicht und ist nicht gezeugt worden. Und Ihm ebenbürtig ist keiner.',
    repetitions: 3,
    source: 'Quran 112:1-4',
  },
  {
    id: 3,
    arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: 'Qul a\'udhu bi-Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-\'uqad. Wa min sharri hasidin idha hasad.',
    translation: 'Sprich: Ich suche Zuflucht beim Herrn des Tagesanbruchs. Vor dem Übel dessen, was Er erschaffen hat. Vor dem Übel der Dunkelheit, wenn sie hereinbricht. Vor dem Übel der Knotenanbläserinnen. Vor dem Übel des Neiders, wenn er neidet.',
    repetitions: 3,
    source: 'Quran 113:1-5',
  },
  {
    id: 4,
    arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ',
    transliteration: 'Qul a\'udhu bi-Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.',
    translation: 'Sprich: Ich suche Zuflucht beim Herrn der Menschen. Dem König der Menschen. Dem Gott der Menschen. Vor dem Übel des sich zurückziehenden Einflüsterers. Der in die Herzen der Menschen einflüstert. Von den Dschinn und den Menschen.',
    repetitions: 3,
    source: 'Quran 114:1-6',
  },
  {
    id: 5,
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Wir sind in den Abend eingetreten und die Herrschaft gehört Allah. Alles Lob gebührt Allah. Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 1,
    source: 'Sahih Muslim 2723',
  },
  {
    id: 6,
    arabic: 'اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَٰهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ',
    transliteration: 'Allahumma inni amsaytu ush-hiduka wa ush-hidu hamalata \'arshika wa mala\'ikataka wa jami\'a khalqika annaka antallahu la ilaha illa anta wahdaka la sharika laka wa anna Muhammadan \'abduka wa rasuluk.',
    translation: 'O Allah, ich bin in den Abend eingetreten und rufe Dich zum Zeugen an, und die Träger Deines Throns, Deine Engel und all Deine Schöpfung, dass Du Allah bist, es keinen Gott gibt außer Dir, allein ohne Partner, und dass Muhammad Dein Diener und Gesandter ist.',
    repetitions: 1,
    source: 'Sunan Abu Dawud 5069',
  },
  {
    id: 7,
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana \'abduka, wa ana \'ala \'ahdika wa wa\'dika mastata\'tu, a\'udhu bika min sharri ma sana\'tu, abu\'u laka bi-ni\'matika \'alayya wa abu\'u bi-dhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa anta.',
    translation: 'O Allah, Du bist mein Herr. Es gibt keinen Gott außer Dir. Du hast mich erschaffen und ich bin Dein Diener. Ich halte an Deinem Bund und Deinem Versprechen fest, so gut ich kann. Ich suche Zuflucht bei Dir vor dem Übel meiner Taten. Ich bekenne Deine Gunst mir gegenüber und bekenne meine Sünde. So vergib mir, denn niemand vergibt die Sünden außer Dir.',
    repetitions: 1,
    source: 'Sahih al-Bukhari 6306',
  },
  {
    id: 8,
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'SubhanAllahi wa bihamdihi',
    translation: 'Preis sei Allah und Ihm gebührt das Lob.',
    repetitions: 100,
    source: 'Sahih Muslim 2692',
  },
  {
    id: 9,
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 10,
    source: 'Sahih Muslim 2693',
  },
  {
    id: 10,
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translation: 'Preis sei Allah.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 11,
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: 'Alles Lob gebührt Allah.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 12,
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: 'Allah ist größer.',
    repetitions: 33,
    source: 'Sahih Muslim 595',
  },
  {
    id: 13,
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: 'Es gibt keinen Gott außer Allah, Ihm allein, ohne Partner. Ihm gehört die Herrschaft und das Lob, und Er hat Macht über alle Dinge.',
    repetitions: 1,
    source: 'Sahih Muslim 595',
  },
];
