export const ARABIC_ALPHABET = [
  {
    id: 1,
    letter: 'ا',
    name: 'Alif',
    transliteration: 'a',
    description: 'Langer "a"-Laut, wie in "Vater"',
    forms: { isolated: 'ا', initial: 'ا', medial: 'ـا', final: 'ـا' },
    example: { word: 'أَسَد', meaning: 'Löwe', transliteration: 'asad' },
  },
  {
    id: 2,
    letter: 'ب',
    name: 'Ba',
    transliteration: 'b',
    description: 'Wie deutsches "b" in "Buch"',
    forms: { isolated: 'ب', initial: 'بـ', medial: 'ـبـ', final: 'ـب' },
    example: { word: 'بَيْت', meaning: 'Haus', transliteration: 'bayt' },
  },
  {
    id: 3,
    letter: 'ت',
    name: 'Ta',
    transliteration: 't',
    description: 'Wie deutsches "t" in "Tisch"',
    forms: { isolated: 'ت', initial: 'تـ', medial: 'ـتـ', final: 'ـت' },
    example: { word: 'تُفَّاح', meaning: 'Apfel', transliteration: 'tuffah' },
  },
  {
    id: 4,
    letter: 'ث',
    name: 'Tha',
    transliteration: 'th',
    description: 'Wie englisches "th" in "think"',
    forms: { isolated: 'ث', initial: 'ثـ', medial: 'ـثـ', final: 'ـث' },
    example: { word: 'ثَلْج', meaning: 'Schnee', transliteration: 'thalj' },
  },
  {
    id: 5,
    letter: 'ج',
    name: 'Jim',
    transliteration: 'j',
    description: 'Wie englisches "j" in "juice"',
    forms: { isolated: 'ج', initial: 'جـ', medial: 'ـجـ', final: 'ـج' },
    example: { word: 'جَمَل', meaning: 'Kamel', transliteration: 'jamal' },
  },
  {
    id: 6,
    letter: 'ح',
    name: 'Ha',
    transliteration: 'ḥ',
    description: 'Starkes "h" aus der Kehle, kein deutsches Äquivalent',
    forms: { isolated: 'ح', initial: 'حـ', medial: 'ـحـ', final: 'ـح' },
    example: { word: 'حَليب', meaning: 'Milch', transliteration: 'halib' },
  },
  {
    id: 7,
    letter: 'خ',
    name: 'Kha',
    transliteration: 'kh',
    description: 'Wie deutsches "ch" in "Bach"',
    forms: { isolated: 'خ', initial: 'خـ', medial: 'ـخـ', final: 'ـخ' },
    example: { word: 'خُبْز', meaning: 'Brot', transliteration: 'khubz' },
  },
  {
    id: 8,
    letter: 'د',
    name: 'Dal',
    transliteration: 'd',
    description: 'Wie deutsches "d" in "Dach"',
    forms: { isolated: 'د', initial: 'د', medial: 'ـد', final: 'ـد' },
    example: { word: 'دَار', meaning: 'Haus/Heim', transliteration: 'dar' },
  },
  {
    id: 9,
    letter: 'ذ',
    name: 'Dhal',
    transliteration: 'dh',
    description: 'Wie englisches "th" in "this"',
    forms: { isolated: 'ذ', initial: 'ذ', medial: 'ـذ', final: 'ـذ' },
    example: { word: 'ذَهَب', meaning: 'Gold', transliteration: 'dhahab' },
  },
  {
    id: 10,
    letter: 'ر',
    name: 'Ra',
    transliteration: 'r',
    description: 'Gerolltes "r", wie im Spanischen',
    forms: { isolated: 'ر', initial: 'ر', medial: 'ـر', final: 'ـر' },
    example: { word: 'رَجُل', meaning: 'Mann', transliteration: 'rajul' },
  },
  {
    id: 11,
    letter: 'ز',
    name: 'Zay',
    transliteration: 'z',
    description: 'Wie deutsches stimmhaftes "s" in "Sonne"',
    forms: { isolated: 'ز', initial: 'ز', medial: 'ـز', final: 'ـز' },
    example: { word: 'زَيْت', meaning: 'Öl', transliteration: 'zayt' },
  },
  {
    id: 12,
    letter: 'س',
    name: 'Sin',
    transliteration: 's',
    description: 'Wie stimmloses "s" in "Maus"',
    forms: { isolated: 'س', initial: 'سـ', medial: 'ـسـ', final: 'ـس' },
    example: { word: 'سَمَاء', meaning: 'Himmel', transliteration: 'sama' },
  },
  {
    id: 13,
    letter: 'ش',
    name: 'Shin',
    transliteration: 'sh',
    description: 'Wie deutsches "sch" in "Schule"',
    forms: { isolated: 'ش', initial: 'شـ', medial: 'ـشـ', final: 'ـش' },
    example: { word: 'شَمْس', meaning: 'Sonne', transliteration: 'shams' },
  },
  {
    id: 14,
    letter: 'ص',
    name: 'Sad',
    transliteration: 'ṣ',
    description: 'Betontes "s", schwerer und dunkler als Sin',
    forms: { isolated: 'ص', initial: 'صـ', medial: 'ـصـ', final: 'ـص' },
    example: { word: 'صَبْر', meaning: 'Geduld', transliteration: 'sabr' },
  },
  {
    id: 15,
    letter: 'ض',
    name: 'Dad',
    transliteration: 'ḍ',
    description: 'Betontes "d", einzigartig im Arabischen',
    forms: { isolated: 'ض', initial: 'ضـ', medial: 'ـضـ', final: 'ـض' },
    example: { word: 'ضَوْء', meaning: 'Licht', transliteration: 'daw' },
  },
  {
    id: 16,
    letter: 'ط',
    name: 'Ta (betont)',
    transliteration: 'ṭ',
    description: 'Betontes "t", schwerer als normales Ta',
    forms: { isolated: 'ط', initial: 'طـ', medial: 'ـطـ', final: 'ـط' },
    example: { word: 'طَعَام', meaning: 'Essen', transliteration: 'ta\'am' },
  },
  {
    id: 17,
    letter: 'ظ',
    name: 'Dha (betont)',
    transliteration: 'ẓ',
    description: 'Betontes "dh", schwerer als normales Dhal',
    forms: { isolated: 'ظ', initial: 'ظـ', medial: 'ـظـ', final: 'ـظ' },
    example: { word: 'ظِلّ', meaning: 'Schatten', transliteration: 'dhil' },
  },
  {
    id: 18,
    letter: 'ع',
    name: 'Ain',
    transliteration: '\'',
    description: 'Kehllaut, kein Äquivalent im Deutschen. Kommt tief aus der Kehle.',
    forms: { isolated: 'ع', initial: 'عـ', medial: 'ـعـ', final: 'ـع' },
    example: { word: 'عِلْم', meaning: 'Wissen', transliteration: '\'ilm' },
  },
  {
    id: 19,
    letter: 'غ',
    name: 'Ghain',
    transliteration: 'gh',
    description: 'Wie französisches "r" in "Paris", gurgelnd',
    forms: { isolated: 'غ', initial: 'غـ', medial: 'ـغـ', final: 'ـغ' },
    example: { word: 'غُرْفَة', meaning: 'Zimmer', transliteration: 'ghurfa' },
  },
  {
    id: 20,
    letter: 'ف',
    name: 'Fa',
    transliteration: 'f',
    description: 'Wie deutsches "f" in "Fisch"',
    forms: { isolated: 'ف', initial: 'فـ', medial: 'ـفـ', final: 'ـف' },
    example: { word: 'فِيل', meaning: 'Elefant', transliteration: 'fil' },
  },
  {
    id: 21,
    letter: 'ق',
    name: 'Qaf',
    transliteration: 'q',
    description: 'Tiefer "k"-Laut aus dem Rachen, weiter hinten als "k"',
    forms: { isolated: 'ق', initial: 'قـ', medial: 'ـقـ', final: 'ـق' },
    example: { word: 'قَمَر', meaning: 'Mond', transliteration: 'qamar' },
  },
  {
    id: 22,
    letter: 'ك',
    name: 'Kaf',
    transliteration: 'k',
    description: 'Wie deutsches "k" in "Kinder"',
    forms: { isolated: 'ك', initial: 'كـ', medial: 'ـكـ', final: 'ـك' },
    example: { word: 'كِتَاب', meaning: 'Buch', transliteration: 'kitab' },
  },
  {
    id: 23,
    letter: 'ل',
    name: 'Lam',
    transliteration: 'l',
    description: 'Wie deutsches "l" in "Licht"',
    forms: { isolated: 'ل', initial: 'لـ', medial: 'ـلـ', final: 'ـل' },
    example: { word: 'لَيْل', meaning: 'Nacht', transliteration: 'layl' },
  },
  {
    id: 24,
    letter: 'م',
    name: 'Mim',
    transliteration: 'm',
    description: 'Wie deutsches "m" in "Mond"',
    forms: { isolated: 'م', initial: 'مـ', medial: 'ـمـ', final: 'ـم' },
    example: { word: 'مَاء', meaning: 'Wasser', transliteration: 'ma\'' },
  },
  {
    id: 25,
    letter: 'ن',
    name: 'Nun',
    transliteration: 'n',
    description: 'Wie deutsches "n" in "Nacht"',
    forms: { isolated: 'ن', initial: 'نـ', medial: 'ـنـ', final: 'ـن' },
    example: { word: 'نُور', meaning: 'Licht', transliteration: 'nur' },
  },
  {
    id: 26,
    letter: 'ه',
    name: 'Ha',
    transliteration: 'h',
    description: 'Leichtes "h" wie in "Haus"',
    forms: { isolated: 'ه', initial: 'هـ', medial: 'ـهـ', final: 'ـه' },
    example: { word: 'هِلَال', meaning: 'Mondsichel', transliteration: 'hilal' },
  },
  {
    id: 27,
    letter: 'و',
    name: 'Waw',
    transliteration: 'w/u',
    description: 'Wie englisches "w" in "water" oder langes "u"',
    forms: { isolated: 'و', initial: 'و', medial: 'ـو', final: 'ـو' },
    example: { word: 'وَرْد', meaning: 'Rose', transliteration: 'ward' },
  },
  {
    id: 28,
    letter: 'ي',
    name: 'Ya',
    transliteration: 'y/i',
    description: 'Wie deutsches "j" in "ja" oder langes "i"',
    forms: { isolated: 'ي', initial: 'يـ', medial: 'ـيـ', final: 'ـي' },
    example: { word: 'يَد', meaning: 'Hand', transliteration: 'yad' },
  },
];
