export const TAJWEED_CATEGORIES = [
  {
    id: 1,
    title: 'Grundlagen',
    icon: '📚',
    rules: [
      {
        id: 'istiaadha',
        name: 'Al-Isti\'adha',
        nameAr: 'الاستعاذة',
        description: 'Die Zufluchtnahme bei Allah vor dem Shaytan vor dem Lesen des Quran.',
        text: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
        transliteration: 'A\'udhu billahi minash-shaytanir-rajim',
        translation: 'Ich suche Zuflucht bei Allah vor dem verfluchten Shaytan',
        explanation: 'Wird vor dem Beginn der Quran-Rezitation gesprochen. Es ist Sunnah (empfohlen) und keine Pflicht.',
      },
      {
        id: 'basmala',
        name: 'Al-Basmala',
        nameAr: 'البسملة',
        description: 'Im Namen Allahs — wird am Anfang jeder Sure gesprochen (außer Sure 9).',
        text: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
        transliteration: 'Bismillahir-Rahmanir-Rahim',
        translation: 'Im Namen Allahs, des Allerbarmers, des Barmherzigen',
        explanation: 'Wird vor jeder Sure rezitiert, außer Sure At-Tawba (9). Bei Al-Fatiha ist sie Teil des ersten Verses.',
      },
    ],
  },
  {
    id: 2,
    title: 'Noon Sakinah & Tanween',
    icon: 'ن',
    rules: [
      {
        id: 'idhar',
        name: 'Idhar (Deutlichkeit)',
        nameAr: 'الإظهار',
        description: 'Noon Sakinah oder Tanween wird deutlich ausgesprochen wenn danach ein Halsbuchstabe folgt.',
        letters: 'ء ه ع ح غ خ',
        lettersName: 'Halsbuchstaben (Huruf al-Halq)',
        example: { text: 'مِنْ عِلْمٍ', transliteration: 'min \'ilmin', explanation: 'Das Noon wird deutlich gesprochen weil Ain folgt' },
        color: '#4CAF50',
      },
      {
        id: 'idgham_ghunna',
        name: 'Idgham mit Ghunna (Verschmelzung mit Nasallaut)',
        nameAr: 'الإدغام بغنة',
        description: 'Noon Sakinah verschmilzt mit dem nächsten Buchstaben und ein Nasallaut (Ghunna) wird 2 Takte gehalten.',
        letters: 'ي ن م و',
        lettersName: 'Buchstaben: Ya, Nun, Mim, Waw (يَنْمُو)',
        example: { text: 'مِن وَلِيٍّ', transliteration: 'miw-waliyyin', explanation: 'Noon verschmilzt mit Waw, Ghunna 2 Takte' },
        color: '#FF9800',
      },
      {
        id: 'idgham_no_ghunna',
        name: 'Idgham ohne Ghunna (Verschmelzung ohne Nasallaut)',
        nameAr: 'الإدغام بغير غنة',
        description: 'Noon Sakinah verschmilzt komplett ohne Nasallaut.',
        letters: 'ل ر',
        lettersName: 'Buchstaben: Lam, Ra',
        example: { text: 'مِن رَبِّهِمْ', transliteration: 'mir-rabbihim', explanation: 'Noon verschmilzt komplett mit Ra, kein Nasallaut' },
        color: '#2196F3',
      },
      {
        id: 'iqlab',
        name: 'Iqlab (Umwandlung)',
        nameAr: 'الإقلاب',
        description: 'Noon Sakinah wird in ein Mim umgewandelt wenn Ba folgt. Ghunna wird 2 Takte gehalten.',
        letters: 'ب',
        lettersName: 'Nur Buchstabe: Ba',
        example: { text: 'مِن بَعْدِ', transliteration: 'mim-ba\'di', explanation: 'Noon wird zu Mim vor Ba, Ghunna 2 Takte' },
        color: '#9C27B0',
      },
      {
        id: 'ikhfa',
        name: 'Ikhfa (Verbergen)',
        nameAr: 'الإخفاء',
        description: 'Noon Sakinah wird verborgen (zwischen Idhar und Idgham) mit Ghunna von 2 Takten.',
        letters: 'ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك',
        lettersName: '15 übrige Buchstaben',
        example: { text: 'مِن قَبْلُ', transliteration: 'min qablu', explanation: 'Noon wird vor Qaf verborgen, Ghunna 2 Takte' },
        color: '#F44336',
      },
    ],
  },
  {
    id: 3,
    title: 'Mim Sakinah',
    icon: 'م',
    rules: [
      {
        id: 'ikhfa_shafawi',
        name: 'Ikhfa Shafawi',
        nameAr: 'الإخفاء الشفوي',
        description: 'Mim Sakinah wird verborgen wenn Ba folgt. Lippen bleiben geschlossen, Ghunna 2 Takte.',
        letters: 'ب',
        example: { text: 'تَرْمِيهِم بِحِجَارَةٍ', transliteration: 'tarmiihim bihijaratin', explanation: 'Mim wird vor Ba verborgen' },
        color: '#9C27B0',
      },
      {
        id: 'idgham_shafawi',
        name: 'Idgham Shafawi',
        nameAr: 'الإدغام الشفوي',
        description: 'Mim Sakinah verschmilzt wenn ein weiteres Mim folgt. Ghunna 2 Takte.',
        letters: 'م',
        example: { text: 'لَهُم مَا', transliteration: 'lahum-ma', explanation: 'Mim verschmilzt mit Mim' },
        color: '#FF9800',
      },
      {
        id: 'idhar_shafawi',
        name: 'Idhar Shafawi',
        nameAr: 'الإظهار الشفوي',
        description: 'Mim Sakinah wird deutlich ausgesprochen vor allen anderen Buchstaben (außer Ba und Mim).',
        letters: 'Alle außer ب und م',
        example: { text: 'أَنْعَمْتَ', transliteration: 'an\'amta', explanation: 'Mim wird deutlich vor Ta gesprochen' },
        color: '#4CAF50',
      },
    ],
  },
  {
    id: 4,
    title: 'Madd (Dehnung)',
    icon: '〰️',
    rules: [
      {
        id: 'madd_tabii',
        name: 'Madd Tabii\'i (natürliche Dehnung)',
        nameAr: 'المد الطبيعي',
        description: 'Grunddehnung von 2 Takten bei Alif, Waw und Ya.',
        example: { text: 'قَالُوا', transliteration: 'qalu', explanation: 'Das Alif nach Lam wird 2 Takte gedehnt' },
        duration: '2 Takte',
        color: '#4CAF50',
      },
      {
        id: 'madd_muttasil',
        name: 'Madd Muttasil (verbundene Dehnung)',
        nameAr: 'المد المتصل',
        description: 'Wenn nach einem Madd-Buchstaben ein Hamza im selben Wort folgt. 4-5 Takte.',
        example: { text: 'جَاءَ', transliteration: 'ja\'a', explanation: 'Alif gefolgt von Hamza im selben Wort: 4-5 Takte' },
        duration: '4-5 Takte',
        color: '#FF9800',
      },
      {
        id: 'madd_munfasil',
        name: 'Madd Munfasil (getrennte Dehnung)',
        nameAr: 'المد المنفصل',
        description: 'Wenn ein Wort mit Madd endet und das nächste Wort mit Hamza beginnt. 4-5 Takte.',
        example: { text: 'بِمَا أُنزِلَ', transliteration: 'bima unzila', explanation: 'Alif am Wortende, Hamza am nächsten Wortanfang' },
        duration: '4-5 Takte',
        color: '#2196F3',
      },
    ],
  },
  {
    id: 5,
    title: 'Qalqalah (Echo)',
    icon: '🔊',
    rules: [
      {
        id: 'qalqalah',
        name: 'Qalqalah',
        nameAr: 'القلقلة',
        description: 'Ein leichtes Echo/Nachschwingen bei 5 Buchstaben wenn sie Sukun haben.',
        letters: 'ق ط ب ج د',
        lettersName: 'Qaf, Ta, Ba, Jim, Dal (قُطْبُ جَدٍّ)',
        example: { text: 'يَخْلُقْ', transliteration: 'yakhluq', explanation: 'Qaf am Wortende mit Sukun: leichtes Echo' },
        explanation: 'Qalqalah Sughra (klein): wenn der Buchstabe in der Wortmitte ist. Qalqalah Kubra (groß): wenn der Buchstabe am Wortende steht — stärkeres Echo.',
        color: '#E91E63',
      },
    ],
  },
];
